apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: finalfour
    tier: frontend
    run: angular-finalfour
  ports: 
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: finalfour
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: finalfour
        tier: frontend
        track: stable
        run: angular-finalfour
    spec:
      containers:
      - name: angular-finalfour
        image: gcr.io/bolg-229922/angular-finalfour:latest
        ports:
        - containerPort: 80
