import { Team } from './team';

export const TEAMS: Team[] = [
  { id: 'auburn', name: 'Auburn', imageUrl: 'auburn.png'},
  { id: 'acu', name: 'ACU', imageUrl: 'acu.png'},
  { id: 'arizonast', name: 'Arizona State', imageUrl: 'arizonast.png'},
  { id: 'baylor', name: 'Baylor', imageUrl: 'baylor.png'},
  { id: 'belmont', name: 'Belmont', imageUrl: 'belmont.png'},
  { id: 'bradley', name: 'Bradley', imageUrl: 'bradley.png'},
  { id: 'buffalo', name: 'Buffalo', imageUrl: 'buffalo.png'},
  { id: 'cincinnati', name: 'Cincinnati', imageUrl: 'cincinnati.png'},
  { id: 'colgate', name: 'Colgate', imageUrl: 'colgate.png'},
  { id: 'duke', name: 'Duke', imageUrl: 'duke.png'},
  { id: 'fdu', name: 'FDU', imageUrl: 'fdu.png'},
  { id: 'florida', name: 'Florida', imageUrl: 'florida.png'},
  { id: 'floridast', name: 'Florida State', imageUrl: 'floridast.png'},
  { id: 'gardnerwebb', name: 'Gardner-Webb', imageUrl: 'gardnerwebb.png'},
  { id: 'georgiast', name: 'Georgia State', imageUrl: 'georgiast.png'},
  { id: 'gonzaga', name: 'Gonzaga', imageUrl: 'gonzaga.png'},
  { id: 'houston', name: 'Houston', imageUrl: 'houston.png'},
  { id: 'iona', name: 'Iona', imageUrl: 'iona.png'},
  { id: 'iowa', name: 'Iowa', imageUrl: 'iowa.png'},
  { id: 'iowast', name: 'Iowa State', imageUrl: 'iowast.png'},
  { id: 'kansas', name: 'Kansas', imageUrl: 'kansas.png'},
  { id: 'kansasst', name: 'Kansas State', imageUrl: 'kansasst.png'},
  { id: 'kentucky', name: 'Kentucky', imageUrl: 'kentucky.png'},
  { id: 'liberty', name: 'Liberty', imageUrl: 'liberty.png'},
  { id: 'louisville', name: 'Louisville', imageUrl: 'louisville.png'},
  { id: 'lsu', name: 'LSU', imageUrl: 'lsu.png'},
  { id: 'marquette', name: 'Marquette', imageUrl: 'marquette.png'},
  { id: 'maryland', name: 'Maryland', imageUrl: 'maryland.png'},
  { id: 'michigan', name: 'Michigan', imageUrl: 'michigan.png'},
  { id: 'michiganst', name: 'Michigan State', imageUrl: 'michiganst.png'},
  { id: 'minnesota', name: 'Minnesota', imageUrl: 'minnesota.png'},
  { id: 'mississippi', name: 'Mississippi', imageUrl: 'mississippi.png'},
  { id: 'mississippist', name: 'Mississippi State', imageUrl: 'mississippist.png'},
  { id: 'montana', name: 'Montana', imageUrl: 'montana.png'},
  { id: 'murrayst', name: 'Murray State', imageUrl: 'murrayst.png'},
  { id: 'nevada', name: 'Nevada', imageUrl: 'nevada.png'},
  { id: 'nmstate', name: 'New Mexico State', imageUrl: 'nmstate.png'},
  { id: 'northcarolina', name: 'North Carolina', imageUrl: 'northcarolina.png'},
  { id: 'northdakotast', name: 'North Dakota State', imageUrl: 'northdakotast.png'},
  { id: 'northeastern', name: 'Northeastern', imageUrl: 'northeastern.png'},
  { id: 'northernkentucky', name: 'Northern Kentucky', imageUrl: 'northernkentucky.png'},
  { id: 'olddominion', name: 'Old Dominion', imageUrl: 'olddominion.png'},
  { id: 'ohiost', name: 'Ohio State', imageUrl: 'ohiost.png'},
  { id: 'oklahoma', name: 'Oklahoma', imageUrl: 'oklahoma.png'},
  { id: 'oregon', name: 'Oregon', imageUrl: 'oregon.png'},
  { id: 'purdue', name: 'Purdue', imageUrl: 'purdue.png'},
  { id: 'saintlouis', name: "Saint Louis", imageUrl: 'saintlouis.png'},
  { id: 'saintmarys', name: "Saint Mary's", imageUrl: 'saintmarys.png'},
  { id: 'setonhall', name: "Seton Hall", imageUrl: 'setonhall.png'},
  { id: 'syracuse', name: "Syracuse", imageUrl: 'syracuse.png'},
  { id: 'tennessee', name: 'Tennessee', imageUrl: 'tennessee.png'},
  { id: 'texastech', name: "Texas Tech", imageUrl: 'texastech.png'},
  { id: 'ucirvine', name: "UC Irvine", imageUrl: 'ucirvine.png'},
  { id: 'ucf', name: "UCF Knights", imageUrl: 'ucf.png'},
  { id: 'utahst', name: "Utah State", imageUrl: 'utahst.png'},
  { id: 'vermont', name: 'Vermont', imageUrl: 'vermont.png'},
  { id: 'villanova', name: 'Villanova', imageUrl: 'villanova.png'},
  { id: 'virginia', name: 'Virginia', imageUrl: 'virginia.png'},
  { id: 'virginiatech', name: 'Virginia Tech', imageUrl: 'virginiatech.png'},
  { id: 'vcu', name: 'VCU Rams', imageUrl: 'vcu.png'},
  { id: 'washington', name: 'Washington', imageUrl: 'washington.png'},
  { id: 'wisconsin', name: 'Wisconsin', imageUrl: 'wisconsin.png'},
  { id: 'wofford', name: 'Wofford', imageUrl: 'wofford.png'},
  { id: 'yale', name: 'Yale', imageUrl: 'yale.png'},

];
