apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalfour
spec:
  selector:
    matchLabels:
      app: finalfour
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: finalfour
        tier: backend
        track: stable
    spec:
      containers:
        - name: finalfour
          image: "gcr.io/bolg-229922/finalfour:latest"
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: username.txt
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password.txt
          volumeMounts:
            - name: certs
              mountPath: "/etc/certs"
              readOnly: true
          command: ["app"]
          ports:
            - name: http
              containerPort: 80
      volumes:
        - name: certs
          secret:
            secretName: db-certs
