apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalfour
spec:
  selector:
    matchLabels:
      app: finalfour
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: finalfour
        tier: backend
        track: stable
    spec:
      containers:
        - name: finalfour
          image: "gcr.io/bolg-229922/finalfour:latest"
          command: ["app"]
          ports:
            - name: http
              containerPort: 80
