// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import team "github.com/tomney/finalfour/backend/app/team"

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *Interface) Get(_a0 string) (team.Team, error) {
	ret := _m.Called(_a0)

	var r0 team.Team
	if rf, ok := ret.Get(0).(func(string) team.Team); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(team.Team)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
